name: Deploy Next 14 to Azure Static Web App

on:
  push:
    branches:
      - temp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or other LTS version
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build-output-to-deploy
          path: ./your_build_output_path

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-output-to-deploy
          path: ./your_build_output_path
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # This should be the path to your app's build output
          api_location: "" # If you have an API, specify its path here
          output_location: "./your_build_output_path"
          skip_app_build: true
          skip_api_build: true
